# Generated by Django 5.2.4 on 2025-08-26 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('bash', 'Bash'), ('html', 'HTML')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('lessonsCompleted', models.JSONField(blank=True, default=dict)),
                ('quizzes', models.JSONField(blank=True, default=dict)),
                ('lastLesson', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
